version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: pizza-app
    container_name: pizza-app
    restart: unless-stopped
    ports:
      - "8000:80"
    volumes:
      - ./storage:/var/www/html/storage
    environment:
      - APP_ENV=production
      - APP_DEBUG=false
      - APP_URL=http://localhost:8000
      - DB_CONNECTION=pgsql
      - DB_HOST=db
      - DB_PORT=5432
      - DB_DATABASE=pizza_db
      - DB_USERNAME=postgres
      - DB_PASSWORD=secret
    depends_on:
      - db
    networks:
      - pizza-network

  db:
    image: postgres:14
    container_name: pizza-db
    restart: unless-stopped
    environment:
      - POSTGRES_DB=pizza_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=secret
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - pizza-network

networks:
  pizza-network:
    driver: bridge

volumes:
  postgres-data: